# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_auto_20170913_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='manager',
            field=models.CharField(choices=[('Майя', 'Майя'), ('Вероника', 'Вероника'), ('Ирина', 'Ирина'), ('-', '-')], default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='join',
            name='tour_direction',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='join',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
