# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='dates',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='tours',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tours',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tours',
            name='tour_program',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tours',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
