# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20170829_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tours',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='tours',
            name='slug',
            field=models.SlugField(blank=True, default='page-slug'),
        ),
        migrations.AddField(
            model_name='tours',
            name='video_embed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tours',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
