# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20170829_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
