# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tours_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='dates',
            field=models.TextField(blank=True, null=True),
        ),
    ]
