# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_auto_20170904_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='head_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tours',
            name='head_keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
