# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_auto_20170906_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tours',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='tours',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='tours',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
