# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_auto_20170908_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
