# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_tours_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='category',
            field=models.CharField(choices=[('bus', 'Bus'), ('avia', 'Avia'), ('individual', 'Individual')], default='bus', max_length=20),
        ),
        migrations.AddField(
            model_name='tours',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tours',
            name='slug',
            field=models.SlugField(blank=True, default='page-slug', unique=True),
        ),
    ]
