# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_auto_20170912_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='short_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
